version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    ports:
      - 35432:5432

  todo-app:
    image: spring-mvc-mybatis:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tododb
    ports:
      - 18888:18888
    depends_on:
      - postgres
